### ISSUE TITLE
U - Optional entry of GP info for user

### ISSUE THREAD

**Issue by edwallitt** [LittleMedHealth/lmh-main#20]
As a user I should be required (but may opt-out) to enter my local GP info so that the info from my Little Med consultations can be sent on to my regular GP.

**Comment by edwallitt** [comment]
Working on ability for user's to be able to add GP information now.

@tessadavis do you think this should be on a per child basis or just on per account basis. 

The reason I ask is that while it is possible the children have different GPs, most will not. If we do add this to each add child form then users will potentially have to enter the same information over and over again.

My feeling is that for the MVP we attach the GP information to the user account, if we get feedback that different children have different GPs then we can change it.

**Comment by tessadavis** [comment]
Sounds fine to me.
